services:
  - type: web
    name: sita-nivas-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
